var STEAM_DEV_KEY = "A71660028EBEEE9D2EA8CF96CE256A56";
var FRIEND_DETAIL = "";
var ERROR_RESULT = { result: { status:15 } };
module.exports = {
  "STEAM_DEV_KEY" : STEAM_DEV_KEY,
  "FRIEND_DETAIL" : FRIEND_DETAIL,
  "ERROR_RESULT" : ERROR_RESULT
}
